---
title: "make_DS_test"
output: html_document
---

```{r setup, echo=FALSE, cache=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(data.table))
suppressMessages(library(dtplyr))
suppressMessages(library(magrittr))
suppressMessages(library(tidyr))
suppressWarnings(library(ggplot2))
suppressMessages(suppressWarnings(library(RODBC)))
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(logging)))
suppressMessages(suppressWarnings(library(ROCR)))
suppressMessages(suppressWarnings(library(caret)))
source("../common_anal/R_fxns.R")
```

```{r fxns, echo=FALSE, cache=FALSE}
load_RAR_specific <- function() {
  
  res1 <- fread("/data/raw_data/PA/select___from_RAR.csv", stringsAsFactors = F, h=T)
  res1$RESULT_ITEM_CODE <- gsub(" |,|\\/|\\#", "_", res1$RESULT_ITEM_CODE )
  res1$ORDER_NAME <- gsub(" ", "_", res1$ORDER_NAME )
  res1$ORDER_START_DATE <- as.POSIXct(res1$ORDER_START_DATE, format = "%d-%b-%Y %H:%M:%S")
  res1$BIRTH_DATE <- as.POSIXct(res1$BIRTH_DATE, format = "%d-%b-%Y %H:%M:%S")
  res1$RESULT_DATE <- as.POSIXct(res1$RESULT_DATE, format = "%d-%b-%Y %H:%M:%S")
  res1$PERFORMED_DATE <- as.POSIXct(res1$PERFORMED_DATE, format = "%d-%b-%Y %H:%M:%S")
  res1$GENDER_MASTER_CODE <- as.factor(res1$GENDER_MASTER_CODE)
  res1$EMPI <- as.character(res1$EMPI)
  
  res1$prov <- res1$ORDERING_PROV
  res1$prov[which(res1$prov=="")] <- res1$ADMITTING_PROV[which(res1$prov=="")]
  
  # res1$Age <- floor(as.numeric(res1$ORDER_START_DATE - res1$BIRTH_DATE)/365.25)
  
  # res1$Val <- numericize(res1$RESULT_VALUE, adjust_down = 0.5)
  
  res1 %<>% 
    dplyr::select(-ORDERING_PROV, -ADMITTING_PROV) %>%
    distinct()
  
  res1
}
load_RAR_surround <- function() {
  res <- read.csv("/data/raw_data/PA/select___from_RAR_surround.csv", as.is = T, h=T, nrows = Inf)
  
  res$RESULT_ITEM_CODE <- gsub(" |,|\\/|\\#", "_", res$RESULT_ITEM_CODE )
  res$ORDER_NAME <- gsub(" ", "_", res$ORDER_NAME )
  res$ORDER_START_DATE <- as.POSIXct(res$ORDER_START_DATE, format = "%d-%b-%Y %H:%M:%S")
  res$RESULT_DATE <- as.POSIXct(res$RESULT_DATE, format = "%d-%b-%Y %H:%M:%S")
  res$EMPI <- as.character(res$EMPI)
  
  res$RAR_DT <- as.POSIXct(res$RAR_DT, format = "%d-%b-%Y %H:%M:%S")
  res$PERFORMED_DATE <- as.POSIXct(res$PERFORMED_DATE, format = "%d-%b-%Y %H:%M:%S")
  
  # Pick a subset of tests
  test_freq <- table(res$RESULT_ITEM_CODE)
  freq_tests <- c(names(test_freq)[which(test_freq > 3000 & !names(test_freq) %in% c("GLUCOSE_POINT_OF_CARE", "ANION_GAP"))], 
                  c("RENIN_ACTIVITY", "RENIN", "ALDOSTERONE", "ALDOSTERONE_LC_MS_MS"))
  others <- res %>% 
    filter(RESULT_ITEM_CODE %in% freq_tests) %>%
    distinct()
  
  #others$Val <- numericize(others$RESULT_VALUE, adjust_down = 0.5)
  
  others
}

idpatients <- function(dats, id_col="EMPI") {
  tmp <- unique(do.call('c',
          lapply(dats, function(dat) {
              unique(dat[[id_col]])
          })))
  
  df <- data.frame(IDs=tmp)

  df %<>% 
    mutate(ID = sample.int(n=nrow(df), replace=FALSE),
             shift = runif(min=-60*60*24*14, max=60*60*24*14, n=nrow(df)))
  
  df
}
deidentify <- function(dat, id_cols=c(), dt_cols=c(), drop_cols=c(), ids=NULL) {
  tmp <- dat
  
  #drop columns
  if (length(drop_cols)) {
    tmp <- tmp %>% dplyr::select(-one_of(drop_cols))
  }
  
  if(is.null(ids)) {
    # deidentify columns
    for (col in id_cols) {
      tmp[[col]] <- as.numeric(as.factor(tmp[[col]]))
    }
  
      # Shift each id by somewhere between -14 and +14 days
    if (length(dt_cols)) {
      tmp %<>%
        group_by_(.dots=id_cols[1]) %>%
        mutate(shift = runif(min=-60*60*24*14, max=60*60*24*14, n=1)) %>%
        mutate_each_(funs(. + shift), dt_cols) %>%
        dplyr::select(-shift)
    }
  } else {
    # Assume a single identifier
    tmp <- merge(tmp, ids, by.x=id_cols[1],
                 by.y="IDs")
    
    
    tmp %<>%
        mutate_each_(funs(. + shift), dt_cols) %>%
      select(-shift, -EMPI)
    
    
  }
  tmp
}

```

```{r get_tests, cache=TRUE}

a <- load_RAR_specific() %>%
  filter(RESULT_ITEM_CODE %in% c("DIRECT_RENIN", "ALDOSTERONE", "RENIN_ACTIVITY", "RENIN")) %>%
  select(-PATIENT_IDENTIFIER, -RESULT_DATE, -PERFORMED_DATE, -VISIT_NUMBER, -ORDER_ITEM_CODE, -prov,
         -ORDER_NAME, -ORDER_ITEM_DESCRIPTION, -PK_ENCOUNTER_ID)

b <- load_RAR_surround() %>%
  select(-PATIENT_IDENTIFIER, -ORDER_NAME, -VISIT_NUMBER, -PK_ENCOUNTER_ID, -ORDER_ITEM_CODE, -ORDER_ITEM_DESCRIPTION, -RESULT_DATE, -PERFORMED_DATE, -DATE_DIFF)


ids <- idpatients(list(a,b))
a <- deidentify(dat=a, id_cols="EMPI", dt_cols=c("ORDER_START_DATE", "BIRTH_DATE"), 
                ids = ids)
b <- deidentify(dat=b, id_cols="EMPI", dt_cols=c("ORDER_START_DATE", "RAR_DT"), 
                ids = ids)

write.csv(x=a, file="~/Downloads/exercise.renin_aldo.csv", row.names=F)
write.csv(x=b, file="~/Downloads/exercise.labs.csv", row.names=F)

#Calculate age
a %<>% 
  mutate(Age = floor(as.numeric(ORDER_START_DATE - BIRTH_DATE)/365.25))

# Merge Renin data
a$RESULT_ITEM_CODE[which(a$RESULT_ITEM_CODE %in% c("DIRECT_RENIN", "RENIN_ACTIVITY", "RENIN"))] <- "RENIN"

# Pick single result for each test and calculate A:R ratio
a %>% 
  filter(RESULT_VALUE != "") %>%
  mutate(RESULT_VALUE = as.numeric(RESULT_VALUE)) %>%
  group_by(ID, ORDER_START_DATE, RESULT_ITEM_CODE) %>%
  slice(1) %>% ungroup() %>%
  group_by(ID, ORDER_START_DATE) %>%
  spread(RESULT_ITEM_CODE, RESULT_VALUE) %>%
  mutate(ALDOSTERONE = as.numeric(ALDOSTERONE),
         RENIN = as.numeric(RENIN),
         RAR = ALDOSTERONE/RENIN) -> a2

# Pick single result for each test
b %>%
  mutate(RESULT_VALUE = as.numeric(RESULT_VALUE)) %>%
  group_by(ID, RAR_DT, RESULT_ITEM_CODE) %>%
  slice(which.min(abs(ORDER_START_DATE - RAR_DT))[1]) %>%
  ungroup() -> b2

# Merge A:R and other data
tmp <- 
  merge(a2, b2 %>% select(-ORDER_START_DATE), 
        by.x=c("ID", "ORDER_START_DATE"), by.y=c("ID", "RAR_DT"))
  
# Spread out other lab data into wide form
tmp %>%
  distinct() %>%
  group_by(ID, ORDER_START_DATE) %>%
  spread(RESULT_ITEM_CODE, RESULT_VALUE) -> tmp2
```

```{r fit_tests}

# Trivial linear regression
lm.fit <- lm(I(log(RAR)) ~ CALCIUM + CARBON_DIOXIDE + CHLORIDE + log(CREATININE) + log(GLUCOSE) +
             #HEMATOCRIT + HEMOGLOBIN + MEAN_CELLULAR_VOLUME + PLATELETS + WBC + log(RDW) + RED_BLOOD_CELLS +
             POTASSIUM +  SODIUM + log(UREA_NITROGEN) +
             Age + GENDER_MASTER_CODE + ALDOSTERONE + RENIN, data=tmp2)
summary(lm.fit)

tmp2$RAR_hi <- with(tmp2, RAR > 30)
  tmp2$RAR_hi <- factor(tmp2$RAR_hi, levels=c(FALSE, TRUE))
  log.fit <- glm(RAR_hi ~ CALCIUM + CARBON_DIOXIDE + CHLORIDE + log(CREATININE) + log(GLUCOSE) +
                   #HEMATOCRIT + HEMOGLOBIN + MEAN_CELLULAR_VOLUME + PLATELETS + WBC + log(RDW) + RED_BLOOD_CELLS +
                   POTASSIUM + log(UREA_NITROGEN) + SODIUM +
                   Age + GENDER_MASTER_CODE, data=tmp2, family=binomial, na.action=na.exclude)
  summary(log.fit)
  log.probs <- predict(log.fit, type="response")
  log.preds <- rep(FALSE, length(log.probs))
  log.preds[which(log.probs > 0.2)] <- TRUE
  log.tab <- table(log.preds, tmp2$RAR_hi)
  accuracy <- mean(log.preds == tmp2$RAR_hi)
  sens <- log.tab[4]/sum(log.tab[3:4])
  ppv <- log.tab[4]/sum(log.tab[c(2,4)])
  spec <- log.tab[1]/sum(log.tab[1:2])
  npv <- log.tab[1]/(sum(log.tab[c(1,3)]))
  
  pr <- prediction(log.probs, tmp2$RAR_hi)
  auc <- performance(pr, measure = "auc")
  auc <- auc@y.values[[1]]

  tmp3 <- tmp2[, c("RAR_hi", "CALCIUM", "CARBON_DIOXIDE", "CHLORIDE", "POTASSIUM",
                 "Age", "GENDER_MASTER_CODE", "ALDOSTERONE")] %>%
  na.omit

train_samples <- sample(x=1:nrow(tmp3), replace = FALSE, size=nrow(tmp3)*.8)
training <- tmp3[train_samples,]
testing <- tmp3[-train_samples,]
ctrl <- trainControl(method = "repeatedcv", number = 10, savePredictions = TRUE)
mod_fit <- train(RAR_hi ~ CALCIUM + CARBON_DIOXIDE + CHLORIDE +
                   POTASSIUM + 
                   Age + GENDER_MASTER_CODE, data=training,
                  method="glm", family="binomial",
                 trControl = ctrl, tuneLength = 5)
mod_fit
pred <- predict(mod_fit, newdata=testing, type="raw")
confusionMatrix(data=pred, testing$RAR_hi)
prob <- predict(mod_fit, newdata=testing, type="prob")
prob_call <- factor(prob[["TRUE"]] > 0.2, levels=c(TRUE, FALSE))
confusionMatrix(data=prob_call, testing$RAR_hi)

pr <- prediction(prob[["TRUE"]], testing$RAR_hi)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc

```
