
SELECT PE.EMPI,PE.MRN_HUP,PE.MRN_PMC,PE.MRN_PAH,PE.MRN_CCH,PE.PATIENT_FNAME,PE.PATIENT_LNAME,PE.GENDER_DESCRIPTION,PE.MARITAL_STATUS_DESCRIPTION,PE.RACE_DESCRIPTION,PE.AGE,PE.VISIT_NUMBER,PE.ENC_DATE,PE.PATIENT_CLASS,
PE.SERVICE_DESCRIPTION,PE.ENC_TYPE_DESCRIPTION,PE.FINANCIAL_CLASS_DESCRIPTION,PE.ENC_STATUS_DESCRIPTION,PE.HEIGHT_INCHES,PE.WEIGHT_LBS,PE.BMI,PE.BP_DIASTOLIC,PE.BP_SYSTOLIC
--,PE.RELIGION_DESCRIPTION , PE.RELIGION_TRADITION , PE.RELIGION_SUBGROUP , PE.RELIGION_GROUP,PE.ENC_DISCHARGE_DATE, 
--PE.LANGUAGE_DESCRIPTION
FROM MDM.PATIENT_ENCOUNTER PE 
WHERE 
  PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
  AND PE.PATIENT_CLASS = 'OUTPATIENT'
  AND MRN_HUP is not NULL
  AND PE.BP_DIASTOLIC is not null and BP_SYSTOLIC is not null
  AND ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
  AND PE.FINANCIAL_CLASS_DESCRIPTION IS NOT NULL
  AND PE.EMPI in(
                    SELECT * FROM 
                    (
                          SELECT  PE.EMPI FROM MDM.PATIENT_ENCOUNTER PE 
                          WHERE PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
                          AND PE.PATIENT_CLASS = 'OUTPATIENT'
                          AND PE.BP_DIASTOLIC is not null and BP_SYSTOLIC is not null
                          AND MRN_HUP is not NULL
                          --AND MRN_HUP='442921029'
                          AND ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
                          AND PE.FINANCIAL_CLASS_DESCRIPTION is not null
                          GROUP BY PE.EMPI
                          HAVING COUNT(PE.VISIT_NUMBER)>=2
                          order by DBMS_RANDOM.VALUE
                      ) WHERE  ROWNUM <= 1000
                      ) 
ORDER BY EMPI,ENC_DATE;


----------------------------all icd9 codes--------------------------------------------------------
---
 
SELECT  DISTINCT ST.EMPI,ST.MRN_HUP,ST.MRN_PMC,ST.MRN_PAH,ST.MRN_CCH, PE.PATIENT_LNAME, PE.PATIENT_FNAME, PE.VISIT_NUMBER, PE.AGE, PE.ENC_DATE , 
PE.PATIENT_CLASS , D.CODING_DATE,  SC.code_type,SC.CODE_STANDARD_NAME,SC.CODE , SC.CODE_DESCRIPTION, SC.SENSITIVE_YN
FROM ST_SR2618986_ENC_MDM_7_5 ST,
  MDM.PATIENT_ENCOUNTER PE,
  MDM.DIAGNOSIS D,
  MDM.R_STANDARD_CODES SC
WHERE 
  ST.EMPI = PE.EMPI
  AND PE.PK_PATIENT_ENCOUNTER_ID = D.FK_PATIENT_ENCOUNTER_ID
  AND D.FK_STANDARD_CODE_ID = SC.PK_STANDARD_CODE_ID
  AND PE.ENC_DATE <'01-JAN-15'
 --AND D.CODING_DATE<'01-JAN-15'
  --AND PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
  --AND PE.PATIENT_CLASS = 'OUTPATIENT'
  --AND PE.MRN_HUP is not NULL
  --AND PE.ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
  --AND (SC.code like '405%' OR SC.code like '401%')
  --'401%')--('405.99','405','405.9','401','401.1','401.0','405.91','405.0','401.9')
  AND SC.code_type = 'DIAGNOSIS'
  AND SC.CODE_STANDARD_NAME ='ICD-9'
  AND SC.SENSITIVE_YN <>1;


--DROP TABLE ST_SR2618986_ALL_ICD9_MDM_7_5
--7_5_ALL_ICD9
--SELECT count(*) FROM ST_SR2618986_ALL_ICD9_MDM_7_5;
--SELECT DISTINCT EMPI FROM ST_SR2618986_ALL_ICD9_MDM_7_5;



----------------------------all med codes--------------------------------------------------------

SELECT  distinct ST.EMPI,ST.MRN_HUP,ST.MRN_PMC,ST.MRN_PAH,ST.MRN_CCH, PE.PATIENT_LNAME, PE.PATIENT_FNAME, PA.PROVIDER_FULL_NAME AS ENC_PROVIDER, PE.VISIT_NUMBER, PE.AGE, PE.ENC_DATE , 
PE.PATIENT_CLASS, D.PK_ORDER_MED_ID
,D.ORDER_NAME, D.ORDER_DATE,D.ORDER_START_DATE,D.Order_Stop_Date,D.Order_Type as ORDER_TYPE,D.Dose,D.Unit_of_Measure,D.Frequency_Name,D.Quantity,D.Refills ,SC.FULL_NAME , SC.GENERIC_NAME ,SC.SIMPLE_GENERIC_NAME, SC.PHARMACY_CLASS,SC.PHARMACY_SUBCLASS
,D.ORDER_STATUS_DESCRIPTION
,P.PROVIDER_FULL_NAME AS ORD_AUTH_PROVIDER,D.ORDER_GROUP
FROM ST_SR2618986_ENC_MDM_7_5 ST,
MDM.PATIENT_ENCOUNTER PE,
MDM.ORDER_MED D,
MDM.R_MEDICATION SC,
MDM.R_PROVIDER P,
MDM.R_PROVIDER PA
WHERE--PE.MRN_HUP = 4473823
ST.EMPI = PE.EMPI
AND PE.PK_PATIENT_ENCOUNTER_ID = D.FK_PATIENT_ENCOUNTER_ID
AND D.FK_MEDICATION_ID = SC.PK_MEDICATION_ID
AND D.FK_PROVIDER_ID = P.PK_PROVIDER_ID (+)
AND PE.FK_ATTENDING_PROVIDER_ID=PA.PK_PROVIDER_ID (+)
AND PE.ENC_DATE <'01-JAN-15'--'11/15/2006' AND PE.ENC_DATE < '11/17/2016' --11/15/06 – 11/16/2016 
AND D.ORDER_DATE <'01-JAN-15'--'11/15/2006' AND PE.ENC_DATE < '11/17/2016' --11/15/06 – 11/16/2016 
AND D.ORDER_STATUS_DESCRIPTION = 'SENT';
--AND PE.PATIENT_CLASS = 'OUTPATIENT'
--AND PE.MRN_HUP is not NULL
--AND PE.ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')

--AND PE.ENC_TYPE_CODE = 'OFFICE VISIT'
--ORDER BY PE.MRN_HUP,PE.ENC_DATE;

--DROP TABLE ST_SR2618986_ALL_MEDS_MDM__7_5;
--SELECT COUNT(*) FROM ST_SR2618986_SENT_MEDS_MDM_7_5;
--SELECT DISTINCT EMPI FROM ST_SR2618986_SENT_MEDS_MDM_7_5;


SELECT distinct EMPI,
  MRN_HUP,
  MRN_PMC,
  MRN_PAH,
  MRN_CCH,
  PATIENT_FNAME,
  PATIENT_LNAME,
  GENDER_DESCRIPTION,
  MARITAL_STATUS_DESCRIPTION,
  RACE_DESCRIPTION
FROM ST_SR2618986_ENC_MDM_7_5;

/*

DROP TABLE ST_SR2618986_ENC_MDM_7_5;

DROP TABLE ST_SR2618986_Daniel_ICD9_MDM;

DROP TABLE ST_SR2618986_Daniel_MEDS_MDM;

SELECT * FROM  ST_SR2618986_Daniel_ENC_MDM;
SELECT count(*) FROM  ST_SR2618986_Daniel_ENC_MDM;
CREATE TABLE ST_SR2618986_1000 nologging AS 
SELECT distinct mrn_hup FROM  ST_SR2618986_Daniel_ENC_MDM;

SELECT * FROM  ST_SR2618986_Daniel_ENC_MDM1
order by mrn_hup;
SELECT count(*) FROM  ST_SR2618986_Daniel_ENC_MDM1;

SELECT count(*) FROM  ST_SR2618986_Daniel_ICD9_MDM;
SELECT count(distinct mrn_hup) FROM  ST_SR2618986_Daniel_ICD9_MDM;
SELECT count(*) FROM  ST_SR2618986_Daniel_ICD9_MDM1;

SELECT count(*) FROM  ST_SR2618986_Daniel_MEDS_MDM;
SELECT count(distinct mrn_hup) FROM  ST_SR2618986_Daniel_ICD9_MDM;





CREATE TABLE ST_SR2618986_Daniel_ICD9_MDM nologging AS 
SELECT  DISTINCT ST.MRN_HUP, PE.PATIENT_LNAME, PE.PATIENT_FNAME, PE.VISIT_NUMBER, PE.AGE, PE.ENC_DATE , 
PE.PATIENT_CLASS , D.CODING_DATE,  SC.code_type,SC.CODE_STANDARD_NAME,SC.CODE , SC.CODE_DESCRIPTION, SC.SENSITIVE_YN
FROM ST_SR2618986_DANIEL_ENC_MDM ST,
MDM.PATIENT_ENCOUNTER PE,
MDM.DIAGNOSIS D,
MDM.R_STANDARD_CODES SC
WHERE 
ST.MRN_HUP = PE.MRN_HUP
AND PE.PK_PATIENT_ENCOUNTER_ID = D.FK_PATIENT_ENCOUNTER_ID
AND D.FK_STANDARD_CODE_ID = SC.PK_STANDARD_CODE_ID
AND PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
AND PE.PATIENT_CLASS = 'OUTPATIENT'
AND PE.MRN_HUP is not NULL
AND PE.ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
AND (SC.code like '405%' OR SC.code like '401%')
--'401%')--('405.99','405','405.9','401','401.1','401.0','405.91','405.0','401.9')
AND SC.code_type = 'DIAGNOSIS'
AND SC.CODE_STANDARD_NAME ='ICD-9'
AND SC.SENSITIVE_YN <>1;

select distinct CODE,CODE_DESCRIPTION from MDM.R_STANDARD_CODES
where (code like '405%' or code like '401%')
AND CODE_TYPE='DIAGNOSIS'
ORDER BY code;


CREATE TABLE ST_SR2618986_Daniel_MEDS_MDM nologging AS 
SELECT  distinct PE.MRN_HUP ,PE.PATIENT_LNAME, PE.PATIENT_FNAME, PA.PROVIDER_FULL_NAME AS ENC_PROVIDER, PE.VISIT_NUMBER, PE.AGE, PE.ENC_DATE , 
PE.PATIENT_CLASS, D.PK_ORDER_MED_ID
,D.ORDER_NAME, D.ORDER_DATE,D.Order_Type as ORDER_TYPE,D.Dose,D.Unit_of_Measure,D.Frequency_Name,D.Quantity,D.Refills ,SC.FULL_NAME , SC.GENERIC_NAME ,SC.SIMPLE_GENERIC_NAME, SC.PHARMACY_CLASS,SC.PHARMACY_SUBCLASS
,D.ORDER_STATUS_DESCRIPTION
,P.PROVIDER_FULL_NAME AS ORD_AUTH_PROVIDER,D.ORDER_GROUP
FROM ST_SR2618986_Daniel_ICD9_MDM ST,
MDM.PATIENT_ENCOUNTER PE,
MDM.ORDER_MED D,
MDM.R_MEDICATION SC,
MDM.R_PROVIDER P,
MDM.R_PROVIDER PA
WHERE--PE.MRN_HUP = 4473823
ST.MRN_HUP = PE.MRN_HUP
AND PE.PK_PATIENT_ENCOUNTER_ID = D.FK_PATIENT_ENCOUNTER_ID
AND D.FK_MEDICATION_ID = SC.PK_MEDICATION_ID
AND D.FK_PROVIDER_ID = P.PK_PROVIDER_ID (+)
AND PE.FK_ATTENDING_PROVIDER_ID=PA.PK_PROVIDER_ID (+)
AND PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'--'11/15/2006' AND PE.ENC_DATE < '11/17/2016' --11/15/06 – 11/16/2016 
AND D.ORDER_DATE >='01-JAN-13' AND D.ORDER_DATE <'01-JAN-15'--'11/15/2006' AND PE.ENC_DATE < '11/17/2016' --11/15/06 – 11/16/2016 
AND PE.PATIENT_CLASS = 'OUTPATIENT'
AND PE.MRN_HUP is not NULL
AND PE.ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
AND D.ORDER_STATUS_DESCRIPTION = 'SENT';
--AND PE.ENC_TYPE_CODE = 'OFFICE VISIT'
--ORDER BY PE.MRN_HUP,PE.ENC_DATE;

SELECT COUNT(*) FROM ST_SR2618986_Daniel_MEDS_MDM 

---
CREATE TABLE ST_SR2618986_Daniel_ALL_ICD9_MDM nologging AS 
SELECT  DISTINCT ST.MRN_HUP, PE.PATIENT_LNAME, PE.PATIENT_FNAME, PE.VISIT_NUMBER, PE.AGE, PE.ENC_DATE , 
PE.PATIENT_CLASS , D.CODING_DATE,  SC.code_type,SC.CODE_STANDARD_NAME,SC.CODE , SC.CODE_DESCRIPTION, SC.SENSITIVE_YN
FROM ST_SR2618986_DANIEL_ENC_MDM ST,
MDM.PATIENT_ENCOUNTER PE,
MDM.DIAGNOSIS D,
MDM.R_STANDARD_CODES SC
WHERE 
ST.MRN_HUP = PE.MRN_HUP
AND PE.PK_PATIENT_ENCOUNTER_ID = D.FK_PATIENT_ENCOUNTER_ID
AND D.FK_STANDARD_CODE_ID = SC.PK_STANDARD_CODE_ID
AND PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
AND PE.PATIENT_CLASS = 'OUTPATIENT'
AND PE.MRN_HUP is not NULL
AND PE.ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
--AND (SC.code like '405%' OR SC.code like '401%')
--'401%')--('405.99','405','405.9','401','401.1','401.0','405.91','405.0','401.9')
AND SC.code_type = 'DIAGNOSIS'
AND SC.CODE_STANDARD_NAME ='ICD-9'
AND SC.SENSITIVE_YN <>1;

*/

SELECT EMPI
--COUNT(DISTINCT(EMPI)) AS TOTAL_DIAG
, COUNT(CODE) AS TOTAL_DIAG
,COUNT(DISTINCT(CODE)) AS UNI_DIAG
, COUNT(CASE WHEN CODE LIKE '%405%' OR CODE LIKE '%401%' THEN 1  ELSE NULL END) AS HTN_DIAG
, COUNT(DISTINCT(CASE WHEN CODE LIKE '%405%' OR CODE LIKE '%401%' THEN 1  ELSE NULL END)) AS HTN_DIAG

FROM ST_SR2618986_ALL_ICD9_MDM_7_5
--WHERE EMPI ='1003207020'-- '1000825644'
GROUP BY EMPI

