SELECT *
into #TEMP1
FROM
(
SELECT
PAT_ENC.PAT_ID,
MRN.IDENTITY_ID AS MRN,
pat_enc.PAT_ENC_CSN_ID,
PAT_ENC.CONTACT_DATE AS ENCOUNTER_DATE,
--PAT_ENC.WEIGHT/16 as WEIGHT,
--pat_ENC.HEIGHT,
--OR_LOG.SURGERY_DATE,
--OR_LOG.LOG_ID,
ZC_DISP_ENC_TYPE.NAME AS ENCOUNTER_TYPE,
CLARITY_DEP.DEPARTMENT_NAME DEPARTMENT,
--cs.PROV_NAME as visit_prov,
CLARITY_SER.PROV_NAME,
HNO_INFO.NOTE_ID,
NOTE_ENC_INFO.CONTACT_SERIAL_NUM AS NOTE_SERIAL_NUM,
NOTE_ENC_INFO.CONTACT_DATE AS NOTE_DATE,
ZC_NOTE_TYPE.NAME AS NOTE_TYPE,
ZC_NOTE_TYPE_IP.NAME IP_NOTE_TYPE,
ZC_NOTE_STATUS.NAME AS NOTE_STATUS,
HNO_NOTE_TEXT.LINE AS NOTE_LINE,
HNO_NOTE_TEXT.NOTE_TEXT,
RANK()OVER (PARTITION BY HNO_INFO.NOTE_ID ORDER BY NOTE_ENC_INFO.CONTACT_DATE_REAL DESC) AS SORT
FROM
PAT_ENC --Encounter table
INNER JOIN PATIENT ON PAT_ENC.PAT_ID = PATIENT.PAT_ID -- Patient table
INNER JOIN IDENTITY_ID AS MRN ON PAT_ENC.PAT_ID = MRN.PAT_ID AND MRN.IDENTITY_TYPE_ID = 100 --HUP MRN
INNER JOIN ZC_DISP_ENC_TYPE ON PAT_ENC.ENC_TYPE_C = ZC_DISP_ENC_TYPE.DISP_ENC_TYPE_C -- Encounter Type
INNER JOIN CLARITY_DEP ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID -- Department table
INNER JOIN HNO_INFO ON PAT_ENC.PAT_ENC_CSN_ID = HNO_INFO.PAT_ENC_CSN_ID -- Main note table
INNER JOIN NOTE_ENC_INFO  ON NOTE_ENC_INFO .NOTE_ID = HNO_INFO.NOTE_ID -- Stores overtime information
INNER JOIN CLARITY_SER cs ON PAT_ENC.VISIT_PROV_ID = cs.PROV_ID --Visit Provider
INNER JOIN CLARITY_SER ON NOTE_ENC_INFO.AUTH_LNKED_PROV_ID = CLARITY_SER.PROV_ID --Note author
INNER JOIN HNO_NOTE_TEXT ON NOTE_ENC_INFO.CONTACT_SERIAL_NUM = HNO_NOTE_TEXT.NOTE_CSN_ID -- Note text
LEFT JOIN HNO_SOURCE_LOG_ID ON NOTE_ENC_INFO.CONTACT_SERIAL_NUM = HNO_SOURCE_LOG_ID.NOTE_CSN_ID -- For notes attached to OR log
LEFT JOIN OR_LOG ON HNO_SOURCE_LOG_ID.SOURCE_LOG_ID = OR_LOG.LOG_ID -- This joins to the main OR log table
LEFT JOIN ZC_NOTE_TYPE ON HNO_INFO.NOTE_TYPE_NOADD_C = ZC_NOTE_TYPE.NOTE_TYPE_C -- Note type
LEFT JOIN ZC_NOTE_STATUS ON NOTE_ENC_INFO.NOTE_STATUS_C = ZC_NOTE_STATUS.NOTE_STATUS_C -- Note status
LEFT JOIN ZC_NOTE_TYPE_IP ON HNO_INFO.IP_NOTE_TYPE_C = ZC_NOTE_TYPE_IP.TYPE_IP_C --Inpatient Note type
WHERE 
--CLARITY_SER.PROV_ID = 'RF2699' --In this example we are filtering on a particular provider
--pat_enc.PAT_ENC_CSN_ID = 446792236-- 158388336
--AND 
PATIENT.PAT_MRN_ID IN(SELECT * FROM #MRN) AND --'051892958'and --'000162453' and
PAT_ENC.CONTACT_DATE > '2013-01-01' and PAT_ENC.CONTACT_DATE < '2015-01-01' --in this example we are limiting to encounters after a certain date
--and PAT_ENC.ENC_TYPE_C = 101
AND ZC_NOTE_TYPE.NOTE_TYPE_C = 19
--and HNO_NOTE_TEXT.NOTE_TEXT LIKE  '%yoga%'
-- OR "%meditation%" OR "%mindfulness%" OR "%acupuncture%"')
) TEMP
WHERE SORT = 1 -- Only show the most recent version of the note
ORDER BY MRN,NOTE_ID,NOTE_SERIAL_NUM ,NOTE_LINE

select * from #temp1
ORDER BY MRN,NOTE_ID,NOTE_SERIAL_NUM ,NOTE_LINE

SELECT MRN,NOTE_ID,
  STUFF(
         (SELECT ',' + NOTE_TEXT
          FROM #TEMP1 
          WHERE NOTE_ID = t1.NOTE_ID 
		  ORDER BY NOTE_ID,NOTE_SERIAL_NUM ,NOTE_LINE
          FOR XML PATH (''))
          , 1, 1, '' ) -- AS NOTE_TEXT 
FROM    #TEMP1 T1
GROUP BY MRN,NOTE_ID
order by MRN,NOTE_ID
