CREATE TABLE /*Enter Table name*/ nologging AS 
SELECT PE.MRN_HUP,PE.PATIENT_FNAME,PE.PATIENT_LNAME,PE.GENDER_DESCRIPTION,PE.MARITAL_STATUS_DESCRIPTION,PE.RACE_DESCRIPTION,PE.AGE,PE.VISIT_NUMBER,PE.ENC_DATE,PE.PATIENT_CLASS,
PE.SERVICE_DESCRIPTION,PE.ENC_TYPE_DESCRIPTION,PE.FINANCIAL_CLASS_DESCRIPTION,PE.ENC_STATUS_DESCRIPTION,PE.HEIGHT_INCHES,PE.WEIGHT_LBS,PE.BMI,PE.BP_DIASTOLIC,PE.BP_SYSTOLIC
--,PE.RELIGION_DESCRIPTION , PE.RELIGION_TRADITION , PE.RELIGION_SUBGROUP , PE.RELIGION_GROUP,PE.ENC_DISCHARGE_DATE, 
--PE.LANGUAGE_DESCRIPTION
FROM MDM.PATIENT_ENCOUNTER PE 
WHERE 
  PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
  AND PE.PATIENT_CLASS = 'OUTPATIENT'
  AND MRN_HUP is not NULL
  AND PE.BP_DIASTOLIC is not null and BP_SYSTOLIC is not null
  AND ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
  AND PE.FINANCIAL_CLASS_DESCRIPTION is not null
  AND PE.MRN_HUP in(
                    SELECT * FROM 
                    (
                          SELECT  PE.MRN_HUP FROM MDM.PATIENT_ENCOUNTER PE 
                          WHERE PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
                          AND PE.PATIENT_CLASS = 'OUTPATIENT'
                          AND PE.BP_DIASTOLIC is not null and BP_SYSTOLIC is not null
                          AND MRN_HUP is not NULL
                          --AND MRN_HUP='442921029'
                          AND ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
                          AND PE.FINANCIAL_CLASS_DESCRIPTION is not null
                          GROUP BY PE.MRN_HUP
                          HAVING COUNT(PE.VISIT_NUMBER)>=2
                          order by DBMS_RANDOM.VALUE
                      ) WHERE  ROWNUM <= 1000
                      ) ;
--ORDER BY MRN_HUP,ENC_DATE;




CREATE TABLE /*Enter Table name*/  nologging AS 
SELECT  DISTINCT ST.MRN_HUP, PE.PATIENT_LNAME, PE.PATIENT_FNAME, PE.VISIT_NUMBER, PE.AGE, PE.ENC_DATE , 
PE.PATIENT_CLASS , D.CODING_DATE,  SC.code_type,SC.CODE_STANDARD_NAME,SC.CODE , SC.CODE_DESCRIPTION, SC.SENSITIVE_YN
FROM ST_SR2618986_DANIEL_ENC_MDM ST,
MDM.PATIENT_ENCOUNTER PE,
MDM.DIAGNOSIS D,
MDM.R_STANDARD_CODES SC
WHERE 
ST.MRN_HUP = PE.MRN_HUP
AND PE.PK_PATIENT_ENCOUNTER_ID = D.FK_PATIENT_ENCOUNTER_ID
AND D.FK_STANDARD_CODE_ID = SC.PK_STANDARD_CODE_ID
AND PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'
AND PE.PATIENT_CLASS = 'OUTPATIENT'
AND PE.MRN_HUP is not NULL
AND PE.ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED')
AND (SC.code like '405%' OR SC.code like '401%')
--'401%')--('405.99','405','405.9','401','401.1','401.0','405.91','405.0','401.9')
AND SC.code_type = 'DIAGNOSIS'
AND SC.CODE_STANDARD_NAME ='ICD-9'
AND SC.SENSITIVE_YN <>1;


CREATE TABLE /*Enter Table name*/  nologging AS 
SELECT  distinct PE.MRN_HUP ,PE.PATIENT_LNAME, PE.PATIENT_FNAME, PE.VISIT_NUMBER, PE.AGE, PE.ENC_DATE , 
PE.PATIENT_CLASS, 
D.ORDER_NAME, D.ORDER_DATE,D.Order_Type as ORDER_TYPE,D.Dose,D.Unit_of_Measure,D.Frequency_Name,D.Quantity,D.Refills ,SC.FULL_NAME , SC.GENERIC_NAME ,SC.SIMPLE_GENERIC_NAME, SC.PHARMACY_CLASS,SC.PHARMACY_SUBCLASS
FROM ST_SR2618986_Daniel_ICD9_MDM ST,
MDM.PATIENT_ENCOUNTER PE,
MDM.ORDER_MED D,
MDM.R_MEDICATION SC
WHERE--PE.MRN_HUP = 4473823
ST.MRN_HUP = PE.MRN_HUP
AND PE.PK_PATIENT_ENCOUNTER_ID = D.FK_PATIENT_ENCOUNTER_ID
AND D.FK_MEDICATION_ID= SC.PK_MEDICATION_ID
AND PE.ENC_DATE >='01-JAN-13' AND PE.ENC_DATE <'01-JAN-15'--'11/15/2006' AND PE.ENC_DATE < '11/17/2016' --11/15/06 – 11/16/2016 
AND D.ORDER_DATE >='01-JAN-13' AND D.ORDER_DATE <'01-JAN-15'--'11/15/2006' AND PE.ENC_DATE < '11/17/2016' --11/15/06 – 11/16/2016 
AND PE.PATIENT_CLASS = 'OUTPATIENT'
AND PE.MRN_HUP is not NULL
AND PE.ENC_STATUS_CODE NOT IN('NO SHOW','CANCELED');
--AND PE.ENC_TYPE_CODE = 'OFFICE VISIT'
--ORDER BY PE.MRN_HUP,PE.ENC_DATE;




